# Generated by Django 3.1.7 on 2021-05-06 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0010_workout_workout_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='video_title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
